#!/bin/bash
set -e -o pipefail -o nounset

rid=https://rid.ncifcrf.gov

function query-rid() {
  local pubmed=$1

  echo "Querying RID" >&2
  curl -fsS $rid/result.php \
    -d virusnm=HIV1 \
    -d subtypenm[]=all \
    -d host=hg19 \
    -d chr[]=all \
    -d pubmed=$pubmed \
    -d site_info[]=origin_id \
    -d site_info[]=chr \
    -d site_info[]=insert_position \
    -d site_info[]=LTR \
    -d site_info[]=insert_orientation \
    -d site_info[]=count \
    -d site_info[]=inserted_gene \
    -d site_info[]=refseq_id \
    -d site_info[]=gene_id \
    -d site_info[]=gene_orientation \
    -d site_info[]=exon_intron \
    -d site_info[]=nearest_gene \
    -d site_info[]=nearest_gene_refseq_id \
    -d site_info[]=nearest_gene_id \
    -d site_info[]=nearest_gene_orientation \
    -d site_info[]=nearest_gene_distance \
    -d site_info[]=comment \
    -d site_info[]=pubmed_id
}

declare -a pubmed_ids
pubmed_ids=(
    15163705    # Han, et al.
    17262715    # Ikeda, et al.
    12843741    # Mack, et al.
    24968937    # Maldarelli, et al.
)

start_line=

for pubmed_id in ${pubmed_ids[@]}; do

    echo "Working on PubMed ID $pubmed_id" >&2
    tsv="$(query-rid $pubmed_id | perl -nle '/(?<=href=)(.+?)(?=>Download\s+Result)/i and print $1')"

    # The tail is to print the TSV header the first time and skip it every
    # subsequent time.
    echo "Downloading TSV" >&2
    curl -fsS "$rid/$tsv" | tail -n +${start_line:-1}
    echo

    start_line=2
done
