#!/bin/bash
set -e -o pipefail -o nounset

GRCh37=$1
orphans=$2

recs join --operation '' \
    landmark,location landmark,location \
    <(recs fromcsv --header $GRCh37) \
    <(recs fromsplit -d $'\t' -k landmark,location <(grep -vE '^#' $orphans || true)) \
    | ./tocsv
