#!/bin/bash
set -e -o pipefail
recs fromcsv -d $'\t' --header source.tsv \
    | recs xform -E transform.recs \
    | ./Ikeda-17262715/annotate-samples \
    | recs tocsv -k "chromosome,gene,info/source_line,location,ltr,ncbi_gene_id,note,orientation_in_gene,orientation_in_reference,sample/original_id,sample/pubmed_id,sample/subject,sample/years_on_art,sample/clone,sample/tissue,sample/tissue_url,sample/disease,sample/genbank,source_name"
