requires 'perl', '5.014';
requires 'DBD::Pg', '3.5.1';
requires 'DBIx::Class';
requires 'DBIx::Class::InflateColumn';
requires 'DBIx::Class::Schema::Loader';
requires 'Getopt::Long::Descriptive';
requires 'Hash::Fold', '0.1.2';
requires 'Hash::Merge';
requires 'JSON::MaybeXS';
requires 'namespace::clean';
requires 'Template::Alloy';
requires 'Text::CSV';
requires 'Time::HiRes';
requires 'Try::Tiny';
requires 'Types::Standard';
requires 'Types::Common::String';
requires 'URI';
