requires 'perl', '5.010';
requires 'DBD::Pg', '3.5.1';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'Getopt::Long::Descriptive';
requires 'Hash::Fold', '0.1.2';
requires 'JSON::PP';
requires 'Text::CSV';
requires 'Time::HiRes';
requires 'Try::Tiny';
requires 'Types::Standard';
requires 'Types::Common::String';
