#!/bin/bash
set -e -o pipefail
recs sort -k info/source_line=n \
    | recs tocsv  -k "info/source_line,landmark,location,ltr,orientation_in_landmark,sample/original_id,sample/pubmed_id,sample/tissue,sample/tissue_url,sample/provirus_activity,environment,source_name"
