#!/bin/bash
set -e -o pipefail
recs fromcsv -d $'\t' -k chr,start,end,sequence_name,score,strand,gene "$@" \
    | recs xform -E transform.recs \
    | recs tocsv -k ltr,landmark,location,orientation_in_landmark,info/sequence_name,sample/pubmed_id,sample/tissue,environment,source_name
