#!/bin/bash
set -e -o pipefail
recs fromcsv --header --fk file "$@" \
    | recs grep '{{CHROMOSOMAL}}' \
    | recs assert -v '{{STRAND}} =~ /^[+-]$/' \
    | recs xform -E transform.recs \
    | ./tocsv
